"""RouterOS script (RSC) generation for the Netwatch dead-man's-switch.

The setup script installs the generated source as a ``/system/script`` and
points a ``/tool/netwatch`` entry's ``down-script`` at it (via
``/system script run <name>``). If the host running the Python watchdog
becomes unreachable, the switch reverts every configured AP port back to the
onboarding VLAN with dot1x active - on its own, independent of the Python
process. This mirrors :meth:`MikroTikClient._apply_onboarding`, but written
in RouterOS scripting language since it has to run on-device.
"""

from __future__ import annotations

from .config import SwitchConfig, VlanConfig

FAILSAFE_SCRIPT_NAME = "ap-switch-watchdog-failsafe-revert"

# Shared helpers for editing RouterOS comma-separated port-list properties
# (tagged/untagged) without disturbing other ports already in the list.
_LIST_HELPERS = """\
:local removeFromList do={
  :local list $1
  :local item $2
  :local result ""
  :foreach p in=[:toarray $list] do={
    :if ($p != $item) do={
      :if ($result = "") do={ :set result $p } else={ :set result ($result . "," . $p) }
    }
  }
  :return $result
}
:local addToList do={
  :local list $1
  :local item $2
  :local found false
  :foreach p in=[:toarray $list] do={ :if ($p = $item) do={ :set found true } }
  :if ($found = true) do={ :return $list } else={
    :if ($list = "") do={ :return $item } else={ :return ($list . "," . $item) }
  }
}
"""


def render_failsafe_script(switch: SwitchConfig, vlans: VlanConfig) -> str:
    """Build the RouterOS script source that reverts ``switch.ap_ports`` to onboarding."""
    lines: list[str] = [
        "# Auto-generated by ap_switch_watchdog.routeros_script - do not edit by hand.",
        f"# Reverts all AP ports on {switch.name} ({switch.bridge}) to the onboarding",
        f"# VLAN {vlans.onboarding} with dot1x active. Run via Netwatch down-script.",
        f':local bridge "{switch.bridge}"',
        ":local port",
        ":local vlanEntry",
        ":local curList",
        "",
        _LIST_HELPERS.rstrip(),
        "",
    ]

    for port in switch.ap_ports:
        lines.append(f"# --- {port} ---")
        lines.append(f':set port "{port}"')
        lines.append("/interface/dot1x/server set [find interface=$port] disabled=no")
        lines.append(
            f"/interface/bridge/port set [find bridge=$bridge interface=$port] pvid={vlans.onboarding}"
        )
        for vid in vlans.trunk:
            lines.extend(_remove_from_vlan(vid, "tagged"))
        lines.extend(_remove_from_vlan(vlans.management, "untagged"))
        lines.extend(_add_to_vlan(vlans.onboarding, "untagged"))
        lines.append("")

    lines.append(':log warning "ap-switch-watchdog: failsafe revert applied"')
    return "\n".join(lines)


def _vlan_lookup(vlan_id: int, field: str) -> list[str]:
    return [
        f":set vlanEntry [/interface/bridge/vlan find where bridge=$bridge and vlan-ids={vlan_id}]",
        f":set curList [/interface/bridge/vlan get $vlanEntry {field}]",
    ]


def _remove_from_vlan(vlan_id: int, field: str) -> list[str]:
    return _vlan_lookup(vlan_id, field) + [
        f"/interface/bridge/vlan set $vlanEntry {field}=[$removeFromList $curList $port]",
    ]


def _add_to_vlan(vlan_id: int, field: str) -> list[str]:
    return _vlan_lookup(vlan_id, field) + [
        f"/interface/bridge/vlan set $vlanEntry {field}=[$addToList $curList $port]",
    ]
